name: Build and deploy website

on:
  push:
    branches: [ master, remodel ]
  workflow_dispatch:

defaults:
  run:
    working-directory: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mkdir ./docs/dist
      run: mkdir -p ./docs/dist
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install NPM packages
      run: npm ci
    - name: Build website
      run: npm run build --if-present
      # output.clean: true にしているので、HTMLファイルのコンパイルを後回しにしている。
    - name: Compile HTML
      run: npm run compile
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        keep_files: true
        publish_dir: ./docs/dist
        exclude_assets: '.github,**/.gitignore'
